version: 1.0.0.{build}

branches:
    only:
        - master

skip_tags: true

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "1.0.0.{build}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: LocalCacher\LocalCacher.sln

before_build:
    - git.exe submodule update --init --recursive
    - nuget restore LocalCacher\LocalCacher.sln
    - nuget restore ElectronicObserverExtended\ElectronicObserver.sln
    - mkdir output
    - ps: (Get-Content LocalCacher\LocalCacher.cs -Encoding UTF8).replace("<BUILD_VERSION>", "$env:APPVEYOR_BUILD_VERSION") | Set-Content LocalCacher\LocalCacher.cs -Encoding UTF8

artifacts:
    - path: output
      name: LocalCacher-$(APPVEYOR_BUILD_VERSION)

deploy:
  provider: GitHub
  auth_token:
    secure: LsaQ0/uL04E4BxlUM1oLH7hMjoc0DtNeHjOpSz4o4+Fhdn7I39HkT5LUwSC6kGuu
  artifact: /.*/
  on:
    branch: master
